services:
  redis:
    image: redis:7-alpine
    container_name: urisik-redis
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: urisik-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: urisik-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: always

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: urisik-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    restart: always

  app:
    image: euuunchae/urisik-app:latest
    container_name: urisik-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
      - elasticsearch
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${HIBERNATE_DDL_AUTO:-update}

      # RDS 연결 정보
      - SPRING_DATASOURCE_URL=jdbc:mysql://urisik-db.crwokauswgl1.ap-northeast-2.rds.amazonaws.com:3306/urisik-db?useSSL=false&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=urisik
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # Redis 연결 정보
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

      # Hibernate 배치 설정
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE=100
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=30
      - SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES=true

      # Kafka 연결 정보
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

      # Elasticsearch 연결 정보
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200

      # JWT 설정
      - JWT_TOKEN_SECRETKEY=${JWT_KEY}
      - JWT_TOKEN_EXPIRATION_ACCESS=14400000
      - JWT_TOKEN_EXPIRATION_REFRESH=604800000


    restart: always

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
